[tool.poetry]
name = "sentinel-websocket-alert-receiver"
version = "0.1.0"
description = "Receives Sentinel alerts via a WebSocket."
authors = ["Dixon Sean Low Yan Feng", "Keith Neo Kai Si"]

[tool.poetry.dependencies]
python = "^3.12"
aiohttp = "^3.10.10"

[tool.poetry.scripts]
sentinel-websocket-alert-receiver = "sentinel_websocket_alert_receiver:entry"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
