[tool.poetry]
name = "sentinel-core"
version = "0.1.0"
description = "Core library for Sentinel."
authors = ["Dixon Sean Low Yan Feng", "Keith Neo Kai Si"]

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^2.1.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
