[tool.poetry]
name = "sentinel-remote-ultralytics"
version = "0.1.0"
description = "Serve an Ultralytics object detector using Litserve."
authors = ["Dixon Sean Low Yan Feng", "Keith Neo Kai Si"]

[tool.poetry.dependencies]
sentinel-core = { path = "../../sentinel-core", develop = true }
sentinel-ultralytics = { path = "../../plugins/sentinel-ultralytics", develop = true }
python = "^3.12"
litserve = "^0.2.3"
numpy = "^2.1.2"

[tool.poetry.scripts]
sentinel-remote-ultralytics = "sentinel_remote_ultralytics:entry"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
